name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
        npm ci
    # - name: tests
    #   run: timeout 1m npm start