name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
        npm ci
    - name: tests
      run: npm test
    - name: Wait for Application to Start
      run: |
        sleep 1
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/status)
        if [ "$response" -eq "200" ]; then
            echo "Application is running successfully."
        else
            echo "Application did not start successfully."
            exit 1  # Mark the job as failed
        fi